// This file is generated by Sapper — do not edit it!
export const routes = [
	
];

if (module.hot) {
	import('C:/Users/opilane/source/repos/site/node_modules/sapper/sapper-dev-client.js').then(client => {
		client.connect(10000);
	});
}